INSERT INTO "BATTERY_TYPE" ("BATTERY_TYPE_ID", "MAX_CHARGE_TIEMS", "TOTAL_CAPACITY", "Name") VALUES ('1', '986', '76.25kWh', '标准续航型');
INSERT INTO "BATTERY_TYPE" ("BATTERY_TYPE_ID", "MAX_CHARGE_TIEMS", "TOTAL_CAPACITY", "Name") VALUES ('4', '819', '96.08kWh', '长续航型');
