// <auto-generated />
using System;
using EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BSS_EFCore.Migrations
{
    [DbContext(typeof(ModelContext))]
    partial class ModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EmployeeMaintenanceItem", b =>
                {
                    b.Property<long>("employeesEmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long>("maintenanceItemsMaintenanceItemId")
                        .HasColumnType("bigint");

                    b.HasKey("employeesEmployeeId", "maintenanceItemsMaintenanceItemId");

                    b.HasIndex("maintenanceItemsMaintenanceItemId");

                    b.ToTable("Employee_MaintenanceItem", (string)null);
                });

            modelBuilder.Entity("EntityFramework.Models.Administrator", b =>
                {
                    b.Property<long>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ADMIN_ID");

                    b.Property<string>("AccountSerial")
                        .HasColumnType("longtext")
                        .HasColumnName("ACCOUNT_SERIAL");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PASSWORD");

                    b.HasKey("AdminId")
                        .HasName("SYS_C009148");

                    b.ToTable("ADMINISTRATOR", (string)null);
                });

            modelBuilder.Entity("EntityFramework.Models.Battery", b =>
                {
                    b.Property<long>("BatteryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("BATTERY_ID");

                    b.Property<int?>("AvailableStatus")
                        .HasColumnType("int")
                        .HasColumnName("AVAILABLE_STATUS");

                    b.Property<long>("BatteryTypeId")
                        .HasColumnType("bigint");

                    b.Property<int>("CurrChargeTimes")
                        .HasColumnType("int")
                        .HasColumnName("CURR_CHARGE_TIMES");

                    b.Property<double>("CurrentCapacity")
                        .HasColumnType("double")
                        .HasColumnName("CURRENT_CAPACITY");

                    b.Property<DateTime>("ManufacturingDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("MANUFACTURING_DATE");

                    b.Property<long?>("switchStationStationId")
                        .HasColumnType("bigint");

                    b.HasKey("BatteryId")
                        .HasName("SYS_C009076");

                    b.HasIndex("BatteryTypeId");

                    b.HasIndex("switchStationStationId");

                    b.ToTable("BATTERY", (string)null);
                });

            modelBuilder.Entity("EntityFramework.Models.BatteryType", b =>
                {
                    b.Property<long>("BatteryTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("BATTERY_TYPE_ID");

                    b.Property<int>("MaxChargeTimes")
                        .HasColumnType("int")
                        .HasColumnName("MAX_CHARGE_TIEMS");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("TotalCapacity")
                        .HasColumnType("longtext")
                        .HasColumnName("TOTAL_CAPACITY");

                    b.HasKey("BatteryTypeId")
                        .HasName("SYS_C009070");

                    b.ToTable("BATTERY_TYPE", (string)null);
                });

            modelBuilder.Entity("EntityFramework.Models.Employee", b =>
                {
                    b.Property<long>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<string>("AccountSerial")
                        .HasColumnType("longtext")
                        .HasColumnName("ACCOUNT_SERIAL");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATE_TIME");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasMaxLength(3)
                        .IsUnicode(true)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("GENDER");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("IDENTITYNUMBER");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("123456")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("POSITIONS");

                    b.Property<byte[]>("ProfilePhoto")
                        .HasColumnType("BLOB")
                        .HasColumnName("PROFILE_PHOTO");

                    b.Property<int>("Salary")
                        .HasColumnType("int")
                        .HasColumnName("SALARY");

                    b.Property<string>("UserName")
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("USERNAME");

                    b.Property<long?>("switchStationStationId")
                        .HasColumnType("bigint");

                    b.HasKey("EmployeeId")
                        .HasName("SYS_C009095");

                    b.HasIndex("switchStationStationId");

                    b.ToTable("EMPLOYEE", (string)null);
                });

            modelBuilder.Entity("EntityFramework.Models.Kpi", b =>
                {
                    b.Property<long>("KpiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("KPI_ID");

                    b.Property<double>("Score")
                        .HasColumnType("double")
                        .HasColumnName("SCORE");

                    b.Property<int>("ServiceFrequency")
                        .HasColumnType("int")
                        .HasColumnName("SERVICE_FREQUENCY");

                    b.Property<double>("TotalPerformance")
                        .HasColumnType("double")
                        .HasColumnName("TOTAL_PERFORMANCE");

                    b.Property<long>("employeeId")
                        .HasColumnType("bigint");

                    b.HasKey("KpiId")
                        .HasName("SYS_C009105");

                    b.HasIndex("employeeId")
                        .IsUnique();

                    b.ToTable("KPI", (string)null);
                });

            modelBuilder.Entity("EntityFramework.Models.MaintenanceItem", b =>
                {
                    b.Property<long>("MaintenanceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MAINTENANCE_ITEM_ID");

                    b.Property<DateTime>("AppointTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("APPOINT_TIME");

                    b.Property<string>("Evaluation")
                        .HasColumnType("longtext");

                    b.Property<string>("MaintenanceLocation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MAINTENANCE_LOCATION");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("NOTE");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int")
                        .HasColumnName("ORDER_STATUS");

                    b.Property<DateTime>("OrderSubmissionTime")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ORDER_SUBMISSION_TIME");

                    b.Property<double>("Score")
                        .HasColumnType("double")
                        .HasColumnName("SCORE");

                    b.Property<DateTime?>("ServiceTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("SERVICE_TIME");

                    b.Property<string>("Title")
                        .HasColumnType("longtext")
                        .HasColumnName("TITLE");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint");

                    b.Property<double>("latitude")
                        .HasColumnType("double");

                    b.Property<double>("longitude")
                        .HasColumnType("double");

                    b.HasKey("MaintenanceItemId")
                        .HasName("SYS_C009117");

                    b.HasIndex("VehicleId");

                    b.ToTable("MAINTENANCE_ITEM", (string)null);
                });

            modelBuilder.Entity("EntityFramework.Models.News", b =>
                {
                    b.Property<long>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ANNOUNCEMENT_ID");

                    b.Property<string>("Contents")
                        .HasMaxLength(2500)
                        .IsUnicode(true)
                        .HasColumnType("varchar(2500)")
                        .HasColumnName("CONTENTS");

                    b.Property<int>("Likes")
                        .HasColumnType("int")
                        .HasColumnName("LIKES");

                    b.Property<int>("PublishPos")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("int")
                        .HasColumnName("PUBLISH_POS");

                    b.Property<DateTime>("PublishTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("PUBLISH_TIME");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TITLE");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int")
                        .HasColumnName("VIEW_COUNT");

                    b.Property<long>("administratorAdminId")
                        .HasColumnType("bigint");

                    b.HasKey("AnnouncementId")
                        .HasName("SYS_C009098");

                    b.HasIndex("administratorAdminId");

                    b.ToTable("NEWS", (string)null);
                });

            modelBuilder.Entity("EntityFramework.Models.OwnerPos", b =>
                {
                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("ADDRESS");

                    b.HasKey("OwnerId")
                        .HasName("SYS_C009099");

                    b.ToTable("OWNERPOS", (string)null);
                });

            modelBuilder.Entity("EntityFramework.Models.SwitchLog", b =>
                {
                    b.Property<long>("SwitchServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SWITCH_SERVICE_ID");

                    b.Property<string>("Evaluation")
                        .HasColumnType("longtext");

                    b.Property<double>("Score")
                        .HasColumnType("double")
                        .HasColumnName("SCORE");

                    b.Property<float>("ServiceFee")
                        .HasColumnType("float");

                    b.Property<DateTime>("SwitchTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("SWITCH_TIME");

                    b.Property<long>("batteryOffBatteryId")
                        .HasColumnType("bigint");

                    b.Property<long>("batteryOnBatteryId")
                        .HasColumnType("bigint");

                    b.Property<long>("switchRequestId")
                        .HasColumnType("bigint");

                    b.HasKey("SwitchServiceId")
                        .HasName("SYS_C009138");

                    b.HasIndex("batteryOffBatteryId");

                    b.HasIndex("batteryOnBatteryId");

                    b.HasIndex("switchRequestId")
                        .IsUnique();

                    b.ToTable("SWITCH_LOG", (string)null);
                });

            modelBuilder.Entity("EntityFramework.Models.SwitchRequest", b =>
                {
                    b.Property<long>("SwitchRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SWITCH_REQUEST_ID");

                    b.Property<long>("BatteryTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NOTES");

                    b.Property<int>("Period")
                        .HasColumnType("int")
                        .HasColumnName("PERIOD");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("POSITION");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("REQUEST_TIME");

                    b.Property<int>("SwitchType")
                        .HasColumnType("int")
                        .HasColumnName("SWITCH_TYPE");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint");

                    b.HasKey("SwitchRequestId")
                        .HasName("SYS_C008772");

                    b.HasIndex("BatteryTypeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("SWITCH_REQUEST", (string)null);
                });

            modelBuilder.Entity("EntityFramework.Models.SwitchStation", b =>
                {
                    b.Property<long>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("STATION_ID");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<int>("AvailableBatteryCount")
                        .HasColumnType("int")
                        .HasColumnName("AVAILABLE_BATTERY_COUNT");

                    b.Property<int>("BatteryCapacity")
                        .HasColumnType("int")
                        .HasColumnName("BATTERY_CAPACITY");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<float>("ElectricityFee")
                        .HasColumnType("float");

                    b.Property<bool>("FailureStatus")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("FAILURE_STATUS");

                    b.Property<double>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("LATITUDE");

                    b.Property<double>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("ParkingFee")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QueueLength")
                        .HasColumnType("int");

                    b.Property<float>("ServiceFee")
                        .HasColumnType("float")
                        .HasColumnName("SERVICE_FEE");

                    b.Property<string>("StationName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("STATION_NAME");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<string>("TimeSpan")
                        .HasColumnType("longtext");

                    b.HasKey("StationId")
                        .HasName("SYS_C009065");

                    b.ToTable("SWITCH_STATION", (string)null);
                });

            modelBuilder.Entity("EntityFramework.Models.Vehicle", b =>
                {
                    b.Property<long>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("VEHICLE_ID");

                    b.Property<long>("BatteryId")
                        .HasColumnType("bigint");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("PLATE_NUMBER");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("PURCHASE_DATE");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.Property<DateTime>("Warranty")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("vehicleOwnerOwnerId")
                        .HasColumnType("bigint");

                    b.Property<long>("vehicleParamVehicleModelId")
                        .HasColumnType("bigint");

                    b.HasKey("VehicleId")
                        .HasName("SYS_C009110");

                    b.HasIndex("BatteryId")
                        .IsUnique();

                    b.HasIndex("vehicleOwnerOwnerId");

                    b.HasIndex("vehicleParamVehicleModelId");

                    b.ToTable("VEHICLE", (string)null);
                });

            modelBuilder.Entity("EntityFramework.Models.VehicleOwner", b =>
                {
                    b.Property<long>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("OWNER_ID");

                    b.Property<string>("AccountSerial")
                        .HasColumnType("longtext")
                        .HasColumnName("ACCOUNT_SERIAL");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("BIRTHDAY");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CREATE_TIME");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Gender")
                        .HasMaxLength(3)
                        .IsUnicode(true)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("GENDER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<byte[]>("ProfilePhoto")
                        .HasColumnType("BLOB")
                        .HasColumnName("PROFILE_PHOTO");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USERNAME");

                    b.HasKey("OwnerId")
                        .HasName("SYS_C009088");

                    b.ToTable("VEHICLE_OWNER", (string)null);
                });

            modelBuilder.Entity("EntityFramework.Models.VehicleParam", b =>
                {
                    b.Property<long>("VehicleModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("VEHICLE_MODEL");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MANUFACTURER");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("int")
                        .HasColumnName("MAX_SPEED");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ServiceTerm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("SERVICE_TERM");

                    b.Property<byte[]>("Sinp")
                        .HasColumnType("BLOB")
                        .HasColumnName("SINP");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TRANSMISSION");

                    b.HasKey("VehicleModelId")
                        .HasName("SYS_C009081");

                    b.ToTable("VEHICLE_PARAM", (string)null);
                });

            modelBuilder.Entity("EmployeeMaintenanceItem", b =>
                {
                    b.HasOne("EntityFramework.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("employeesEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.MaintenanceItem", null)
                        .WithMany()
                        .HasForeignKey("maintenanceItemsMaintenanceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityFramework.Models.Battery", b =>
                {
                    b.HasOne("EntityFramework.Models.BatteryType", "batteryType")
                        .WithMany("batteries")
                        .HasForeignKey("BatteryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.SwitchStation", "switchStation")
                        .WithMany("batteries")
                        .HasForeignKey("switchStationStationId");

                    b.Navigation("batteryType");

                    b.Navigation("switchStation");
                });

            modelBuilder.Entity("EntityFramework.Models.Employee", b =>
                {
                    b.HasOne("EntityFramework.Models.SwitchStation", "switchStation")
                        .WithMany("employees")
                        .HasForeignKey("switchStationStationId");

                    b.Navigation("switchStation");
                });

            modelBuilder.Entity("EntityFramework.Models.Kpi", b =>
                {
                    b.HasOne("EntityFramework.Models.Employee", "employee")
                        .WithOne("kpi")
                        .HasForeignKey("EntityFramework.Models.Kpi", "employeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");
                });

            modelBuilder.Entity("EntityFramework.Models.MaintenanceItem", b =>
                {
                    b.HasOne("EntityFramework.Models.Vehicle", "vehicle")
                        .WithMany("maintenanceItems")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("vehicle");
                });

            modelBuilder.Entity("EntityFramework.Models.News", b =>
                {
                    b.HasOne("EntityFramework.Models.Administrator", "administrator")
                        .WithMany("news")
                        .HasForeignKey("administratorAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("administrator");
                });

            modelBuilder.Entity("EntityFramework.Models.OwnerPos", b =>
                {
                    b.HasOne("EntityFramework.Models.VehicleOwner", "vehicleowner")
                        .WithMany("ownerpos")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("vehicleowner");
                });

            modelBuilder.Entity("EntityFramework.Models.SwitchLog", b =>
                {
                    b.HasOne("EntityFramework.Models.Battery", "batteryOff")
                        .WithMany("switchLogsOff")
                        .HasForeignKey("batteryOffBatteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.Battery", "batteryOn")
                        .WithMany("switchLogsOn")
                        .HasForeignKey("batteryOnBatteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.SwitchRequest", "switchrequest")
                        .WithOne("switchLog")
                        .HasForeignKey("EntityFramework.Models.SwitchLog", "switchRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("batteryOff");

                    b.Navigation("batteryOn");

                    b.Navigation("switchrequest");
                });

            modelBuilder.Entity("EntityFramework.Models.SwitchRequest", b =>
                {
                    b.HasOne("EntityFramework.Models.BatteryType", "batteryType")
                        .WithMany("switchRequests")
                        .HasForeignKey("BatteryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.Employee", "employee")
                        .WithMany("switchRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.Vehicle", "vehicle")
                        .WithMany("switchRequests")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("batteryType");

                    b.Navigation("employee");

                    b.Navigation("vehicle");
                });

            modelBuilder.Entity("EntityFramework.Models.Vehicle", b =>
                {
                    b.HasOne("EntityFramework.Models.Battery", "Battery")
                        .WithOne("vehicle")
                        .HasForeignKey("EntityFramework.Models.Vehicle", "BatteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.VehicleOwner", "vehicleOwner")
                        .WithMany("vehicles")
                        .HasForeignKey("vehicleOwnerOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework.Models.VehicleParam", "vehicleParam")
                        .WithMany("vehicles")
                        .HasForeignKey("vehicleParamVehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Battery");

                    b.Navigation("vehicleOwner");

                    b.Navigation("vehicleParam");
                });

            modelBuilder.Entity("EntityFramework.Models.Administrator", b =>
                {
                    b.Navigation("news");
                });

            modelBuilder.Entity("EntityFramework.Models.Battery", b =>
                {
                    b.Navigation("switchLogsOff");

                    b.Navigation("switchLogsOn");

                    b.Navigation("vehicle");
                });

            modelBuilder.Entity("EntityFramework.Models.BatteryType", b =>
                {
                    b.Navigation("batteries");

                    b.Navigation("switchRequests");
                });

            modelBuilder.Entity("EntityFramework.Models.Employee", b =>
                {
                    b.Navigation("kpi")
                        .IsRequired();

                    b.Navigation("switchRequests");
                });

            modelBuilder.Entity("EntityFramework.Models.SwitchRequest", b =>
                {
                    b.Navigation("switchLog")
                        .IsRequired();
                });

            modelBuilder.Entity("EntityFramework.Models.SwitchStation", b =>
                {
                    b.Navigation("batteries");

                    b.Navigation("employees");
                });

            modelBuilder.Entity("EntityFramework.Models.Vehicle", b =>
                {
                    b.Navigation("maintenanceItems");

                    b.Navigation("switchRequests");
                });

            modelBuilder.Entity("EntityFramework.Models.VehicleOwner", b =>
                {
                    b.Navigation("ownerpos");

                    b.Navigation("vehicles");
                });

            modelBuilder.Entity("EntityFramework.Models.VehicleParam", b =>
                {
                    b.Navigation("vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
