DECLARE
    v_file_handle1 UTL_FILE.FILE_TYPE;
    v_file_handle2 UTL_FILE.FILE_TYPE;
    v_file_handle3 UTL_FILE.FILE_TYPE;
    v_file_handle4 UTL_FILE.FILE_TYPE;
    v_file_handle5 UTL_FILE.FILE_TYPE;
    v_file_handle6 UTL_FILE.FILE_TYPE;
    v_file_handle7 UTL_FILE.FILE_TYPE;
    v_file_handle8 UTL_FILE.FILE_TYPE;
    v_file_handle9 UTL_FILE.FILE_TYPE;
    v_file_handle10 UTL_FILE.FILE_TYPE;
    pic1 BLOB;
    pic2 BLOB;
    pic3 BLOB;
    pic4 BLOB;
    pic5 BLOB;
    pic6 BLOB;
    pic7 BLOB;
    pic8 BLOB;
    pic9 BLOB;
    pic10 BLOB;
BEGIN
    v_file_handle1 := UTL_FILE.FOPEN('C:\Users\Ayalyt\Desktop\蔚来车照', 'ec6-desktop.png', 'R', 32767);
    v_file_handle2 := UTL_FILE.FOPEN('C:\Users\Ayalyt\Desktop\蔚来车照', 'es7-desktop.png', 'R', 32767);
    v_file_handle3 := UTL_FILE.FOPEN('C:\Users\Ayalyt\Desktop\蔚来车照', 'et5-desktop.png', 'R', 32767);
    v_file_handle4 := UTL_FILE.FOPEN('C:\Users\Ayalyt\Desktop\蔚来车照', 'et7-desktop.png', 'R', 32767);
    v_file_handle5 := UTL_FILE.FOPEN('C:\Users\Ayalyt\Desktop\蔚来车照', 'vehicle-slider-ec7-desktop.jpg', 'R', 32767);
    v_file_handle6 := UTL_FILE.FOPEN('C:\Users\Ayalyt\Desktop\蔚来车照', 'vehicle-slider-es6-desktop.jpg', 'R', 32767);
    v_file_handle7 := UTL_FILE.FOPEN('C:\Users\Ayalyt\Desktop\蔚来车照', 'vehicle-slider-es8-desktop.jpg', 'R', 32767);
    v_file_handle8 := UTL_FILE.FOPEN('C:\Users\Ayalyt\Desktop\蔚来车照', 'vehicle-slider-et5-desktop.jpg', 'R', 32767);
    v_file_handle9 := UTL_FILE.FOPEN('C:\Users\Ayalyt\Desktop\蔚来车照', 'vehicle-slider-eve-desktop.jpg', 'R', 32767);
    v_file_handle10 := UTL_FILE.FOPEN('C:\Users\Ayalyt\Desktop\蔚来车照', 'vehicle-slider-ec5-desktop.jpg', 'R', 32767);
    DBMS_LOB.createtemporary(pic1, TRUE);
    DBMS_LOB.createtemporary(pic2, TRUE);
    DBMS_LOB.createtemporary(pic3, TRUE);
    DBMS_LOB.createtemporary(pic4, TRUE);
    DBMS_LOB.createtemporary(pic5, TRUE);
    DBMS_LOB.createtemporary(pic6, TRUE);
    DBMS_LOB.createtemporary(pic7, TRUE);
    DBMS_LOB.createtemporary(pic8, TRUE);
    DBMS_LOB.createtemporary(pic9, TRUE);
    DBMS_LOB.createtemporary(pic10, TRUE);   
    UTL_FILE.GET_RAW(v_file_handle1, pic1, DBMS_LOB.GETLENGTH(pic1));
    UTL_FILE.GET_RAW(v_file_handle2, pic2, DBMS_LOB.GETLENGTH(pic2));
    UTL_FILE.GET_RAW(v_file_handle3, pic3, DBMS_LOB.GETLENGTH(pic3));
    UTL_FILE.GET_RAW(v_file_handle4, pic4, DBMS_LOB.GETLENGTH(pic4));
    UTL_FILE.GET_RAW(v_file_handle5, pic5, DBMS_LOB.GETLENGTH(pic5));
    UTL_FILE.GET_RAW(v_file_handle6, pic6, DBMS_LOB.GETLENGTH(pic6));
    UTL_FILE.GET_RAW(v_file_handle7, pic7, DBMS_LOB.GETLENGTH(pic7));
    UTL_FILE.GET_RAW(v_file_handle8, pic8, DBMS_LOB.GETLENGTH(pic8));
    UTL_FILE.GET_RAW(v_file_handle9, pic9, DBMS_LOB.GETLENGTH(pic9));
    UTL_FILE.GET_RAW(v_file_handle10, pic10, DBMS_LOB.GETLENGTH(pic10));

    INSERT INTO "VEHICLE_PARAM" ("VEHICLE_MODEL", "ModelName", "TRANSMISSION", "SERVICE_TERM", "MANUFACTURER", "MAX_SPEED", "SNIP") VALUES ('1', '蔚来EVE', '前感应异步/后永磁同步电机', TO_TIMESTAMP('1990-06-03 09:55:41.0000000', 'SYYYY-MM-DD HH24:MI:SS:FF7'), '蔚来电驱动系统制造基地（南京）', '363', pic1);
    INSERT INTO "VEHICLE_PARAM" ("VEHICLE_MODEL", "ModelName", "TRANSMISSION", "SERVICE_TERM", "MANUFACTURER", "MAX_SPEED", "SNIP") VALUES ('2', '蔚来ES8', '感应异步电机', TO_TIMESTAMP('2014-01-09 00:20:48.0000000', 'SYYYY-MM-DD HH24:MI:SS:FF7'), '蔚来全球极限性能研发中心（伦敦）', '305', pic2);
    INSERT INTO "VEHICLE_PARAM" ("VEHICLE_MODEL", "ModelName", "TRANSMISSION", "SERVICE_TERM", "MANUFACTURER", "MAX_SPEED", "SNIP") VALUES ('3', '蔚来ET5T', '前感应异步/后永磁同步电机', TO_TIMESTAMP('2016-02-18 11:19:26.0000000', 'SYYYY-MM-DD HH24:MI:SS:FF7'), '蔚来全球自动驾驶研发中心（圣何塞）', '344', pic3);
    INSERT INTO "VEHICLE_PARAM" ("VEHICLE_MODEL", "ModelName", "TRANSMISSION", "SERVICE_TERM", "MANUFACTURER", "MAX_SPEED", "SNIP") VALUES ('5', '蔚来EC6', '单一永磁同步电机', TO_TIMESTAMP('2018-10-06 20:13:36.0000000', 'SYYYY-MM-DD HH24:MI:SS:FF7'), '蔚来全球软件研发中心（北京）', '285', pic4);
    INSERT INTO "VEHICLE_PARAM" ("VEHICLE_MODEL", "ModelName", "TRANSMISSION", "SERVICE_TERM", "MANUFACTURER", "MAX_SPEED", "SNIP") VALUES ('7', '蔚来ET5', '前感应异步/后永磁同步电机', TO_TIMESTAMP('2001-08-29 11:45:55.0000000', 'SYYYY-MM-DD HH24:MI:SS:FF7'), '蔚来车队总部（伦敦）', '272', pic5);
    INSERT INTO "VEHICLE_PARAM" ("VEHICLE_MODEL", "ModelName", "TRANSMISSION", "SERVICE_TERM", "MANUFACTURER", "MAX_SPEED", "SNIP") VALUES ('8', '蔚来EC7', '感应异步电机', TO_TIMESTAMP('2016-02-27 22:10:19.0000000', 'SYYYY-MM-DD HH24:MI:SS:FF7'), '蔚来全球自动驾驶研发中心（圣何塞）', '244', pic6);
    INSERT INTO "VEHICLE_PARAM" ("VEHICLE_MODEL", "ModelName", "TRANSMISSION", "SERVICE_TERM", "MANUFACTURER", "MAX_SPEED", "SNIP") VALUES ('10', '蔚来EP9', '单一永磁同步电机', TO_TIMESTAMP('2002-07-10 11:00:28.0000000', 'SYYYY-MM-DD HH24:MI:SS:FF7'), '蔚来车队总部（伦敦）', '345', pic7);
    INSERT INTO "VEHICLE_PARAM" ("VEHICLE_MODEL", "ModelName", "TRANSMISSION", "SERVICE_TERM", "MANUFACTURER", "MAX_SPEED", "SNIP") VALUES ('11', '蔚来ES6', '单一永磁同步电机', TO_TIMESTAMP('2017-04-27 19:56:59.0000000', 'SYYYY-MM-DD HH24:MI:SS:FF7'), '蔚来整车制造技术基地（合肥）', '320', pic8);
    INSERT INTO "VEHICLE_PARAM" ("VEHICLE_MODEL", "ModelName", "TRANSMISSION", "SERVICE_TERM", "MANUFACTURER", "MAX_SPEED", "SNIP") VALUES ('19', '蔚来ET7', '前感应异步/后永磁同步电机', TO_TIMESTAMP('2022-08-17 11:17:24.0000000', 'SYYYY-MM-DD HH24:MI:SS:FF7'), '蔚来全球软件研发中心（北京）', '306', pic9);
    INSERT INTO "VEHICLE_PARAM" ("VEHICLE_MODEL", "ModelName", "TRANSMISSION", "SERVICE_TERM", "MANUFACTURER", "MAX_SPEED", "SNIP") VALUES ('23', '蔚来ES7', '单一永磁同步电机', TO_TIMESTAMP('2016-07-24 11:28:16.0000000', 'SYYYY-MM-DD HH24:MI:SS:FF7'), '蔚来车队总部（伦敦）', '357', pic10);
    
    UTL_FILE.FCLOSE(v_file_handle1);
    UTL_FILE.FCLOSE(v_file_handle2);
    UTL_FILE.FCLOSE(v_file_handle3);
    UTL_FILE.FCLOSE(v_file_handle4);
    UTL_FILE.FCLOSE(v_file_handle5);
    UTL_FILE.FCLOSE(v_file_handle6);
    UTL_FILE.FCLOSE(v_file_handle7);
    UTL_FILE.FCLOSE(v_file_handle8);
    UTL_FILE.FCLOSE(v_file_handle9);
    UTL_FILE.FCLOSE(v_file_handle10);
    DBMS_LOB.freetemporary(pic1);
    DBMS_LOB.freetemporary(pic2);
    DBMS_LOB.freetemporary(pic3);
    DBMS_LOB.freetemporary(pic4);
    DBMS_LOB.freetemporary(pic5);
    DBMS_LOB.freetemporary(pic6);
    DBMS_LOB.freetemporary(pic7);
    DBMS_LOB.freetemporary(pic8);
    DBMS_LOB.freetemporary(pic9);
    DBMS_LOB.freetemporary(pic10);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('插入成功');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
        ROLLBACK;
END;